### ISSUE TITLE
rake couchdb:create

### ISSUE THREAD

**Issue by optikfluffel** [couchrest/couchrest#89]
Hey there.

I use this default configuration as `couchdb.yml`:

```
development: &development
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: app
  suffix: development
  username:
  password:

test:
  <<: *development
  suffix: test

production:
  protocol: 'https'
  host: localhost
  port: 5984
  prefix: app
  suffix: production
  username: root
  password: 123
```

And when I do `rake couchdb:create` it doesn't work for me. I only get this trace:

```
/Users/user/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task_manager.rb:49:in `[]'
/Users/user/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:115:in `invoke_task'
/Users/user/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/Users/user/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/Users/user/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/Users/user/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/user/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/Users/user/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/Users/user/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/user/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/Users/user/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/Users/user/.rvm/gems/ruby-1.9.3-p194@global/bin/rake:19:in `load'
/Users/user/.rvm/gems/ruby-1.9.3-p194@global/bin/rake:19:in `<main>'
/Users/user/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `eval'
/Users/user/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `<main>'
```
